/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace AGVSystemCommonNet6.GPMRosMessageNet.Actions
{
    public class TaskCommandFeedback : Message
    {
        public const string RosMessageName = "gpm_msgs/TaskCommandFeedback";

        public PoseStamped base_position { get; set; }

        public TaskCommandFeedback()
        {
            this.base_position = new PoseStamped();
        }

        public TaskCommandFeedback(PoseStamped base_position)
        {
            this.base_position = base_position;
        }
    }
}
