/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using AGVSystemCommonNet6.GPMRosMessageNet.Actions;
using RosSharp.RosBridgeClient.Actionlib;

namespace AGVSystemCommonNet6.AGVSystemCommonNet6.GPMRosMessageNet.Actions
{
    public class TaskCommandAction : RosSharp.RosBridgeClient.Action<TaskCommandActionGoal, TaskCommandActionResult, TaskCommandActionFeedback, TaskCommandGoal, TaskCommandResult, TaskCommandFeedback>
    {
        public const string RosMessageName = "gpm_msgs/TaskCommandAction";

        public TaskCommandAction() : base()
        {
            this.action_goal = new TaskCommandActionGoal();
            this.action_result = new TaskCommandActionResult();
            this.action_feedback = new TaskCommandActionFeedback();
        }

    }
}
