/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace AGVSystemCommonNet6.GPMRosMessageNet.Actions
{
    public class TaskCommandActionResult : RosSharp.RosBridgeClient.ActionResult<TaskCommandResult>
    {
        public const string RosMessageName = "gpm_msgs/TaskCommandActionResult";

        public TaskCommandActionResult() : base()
        {
            this.result = new TaskCommandResult();
        }

        public TaskCommandActionResult(Header header, GoalStatus status, TaskCommandResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
