/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace AGVSystemCommonNet6.GPMRosMessageNet.Actions
{
    public class TaskCommandActionGoal : RosSharp.RosBridgeClient.ActionGoal<TaskCommandGoal>
    {
        public const string RosMessageName = "gpm_msgs/TaskCommandActionGoal";

        public TaskCommandActionGoal() : base()
        {
            this.goal = new TaskCommandGoal();
        }

        public TaskCommandActionGoal(Header header, GoalID goal_id, TaskCommandGoal goal) : base(header, goal_id)
        {
            this.goal = goal;
        }
    }
}
